# This file was generated by GoReleaser. DO NOT EDIT.
cask "vmbb" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "7c367b9ccb500e0c11a2100a937ecb6edb9744e5be43bb606031868d2d90066f"
      url "https://github.com/virtualmin/virtualmin-backup-browser/releases/download/v#{version}/vmbb_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "abf1af0617f958557a84a2a4579b9a182195e9cc3111653edd8d5f329869c07e"
      url "https://github.com/virtualmin/virtualmin-backup-browser/releases/download/v#{version}/vmbb_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a2386cda0b8c596e81e5ac46fdaeb21ac893cd3d226b9c65d24b816636226e2b"
      url "https://github.com/virtualmin/virtualmin-backup-browser/releases/download/v#{version}/vmbb_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ac2f424daa3f4180d198032d948978ccb662fa977da30d11dbc65c874655072d"
      url "https://github.com/virtualmin/virtualmin-backup-browser/releases/download/v#{version}/vmbb_#{version}_linux_arm64.tar.gz"
    end
  end

  name "vmbb"
  desc "Browse Virtualmin backup archives without Perl, GNU tar, or extra tools"
  homepage "https://github.com/virtualmin/virtualmin-backup-browser"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vmbb"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vmbb"]
    end
  end

  # No zap stanza required

end
