# This file was generated by GoReleaser. DO NOT EDIT.
cask "vmbb" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "d03ed76d4088390c4df8b63cc9995b4a142e79930b74480f0d9599c67b1b1d8d"
      url "https://github.com/virtualmin/virtualmin-backup-browser/releases/download/v#{version}/vmbb_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cfec4ccabfcc071ec7a62d244cbb94d9a1a3e84e2ce63410cc1d4acd652d55ee"
      url "https://github.com/virtualmin/virtualmin-backup-browser/releases/download/v#{version}/vmbb_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0e0627c38f5bc2648e86ffbb429f03d795a746d087f61226c51119cf3dee5009"
      url "https://github.com/virtualmin/virtualmin-backup-browser/releases/download/v#{version}/vmbb_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "68394c686bedc64e1aabd5c0f1454d81c84ca441108234025d3b1ebd037f2631"
      url "https://github.com/virtualmin/virtualmin-backup-browser/releases/download/v#{version}/vmbb_#{version}_linux_arm64.tar.gz"
    end
  end

  name "vmbb"
  desc "Browse Virtualmin backup archives without Perl, GNU tar, or extra tools"
  homepage "https://github.com/virtualmin/virtualmin-backup-browser"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vmbb"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vmbb"]
    end
  end

  # No zap stanza required

end
