# This file was generated by GoReleaser. DO NOT EDIT.
cask "vmbb" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "4c52102a01df30996d78b3a5c63e174267292fc7d265ffdc2332b2bc0a0d177a"
      url "https://github.com/virtualmin/virtualmin-backup-browser/releases/download/v#{version}/vmbb_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "92fc9bb81439d0fd6fd7fa0dacd1681b11cf81244c587e1536f976a1f2f585da"
      url "https://github.com/virtualmin/virtualmin-backup-browser/releases/download/v#{version}/vmbb_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d98a612a8c57b6bdb28c5151880f9cc212e1c16dba52d47959ff379a56e676a8"
      url "https://github.com/virtualmin/virtualmin-backup-browser/releases/download/v#{version}/vmbb_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cc0fc528a0db1a661504d19f541f545ac8619df50ecca7dae06eca2b32764937"
      url "https://github.com/virtualmin/virtualmin-backup-browser/releases/download/v#{version}/vmbb_#{version}_linux_arm64.tar.gz"
    end
  end

  name "vmbb"
  desc "Browse Virtualmin backup archives without Perl, GNU tar, or extra tools"
  homepage "https://github.com/virtualmin/virtualmin-backup-browser"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vmbb"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vmbb"]
    end
  end

  # No zap stanza required

end
